package com.agilecrm.contact;

import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

import com.agilecrm.db.ObjectifyGenericDao;

/**
 * <code>Tag</code> class stores tags (of a contact in particular). The id of
 * the created entity is not generated by appengine, the tag name itself is
 * taken as its id, to prevent existence of duplicate tag names.
 * <p>
 * This class always uses its parameterized constructor to create an entity
 * </p>
 * 
 * @author
 * 
 */
@XmlRootElement
public class Tag
{

    /**
     * Tag name is taken as id
     */
    @Id
    public String tag;

    // Dao
    private static ObjectifyGenericDao<Tag> dao = new ObjectifyGenericDao<Tag>(
	    Tag.class);

    /**
     * Default constructor
     */
    Tag()
    {

    }

    /**
     * Creates a tag with its name assigning to id
     * 
     * @param tag
     */
    Tag(String tag)
    {
	this.tag = tag;
    }

    /**
     * Adds a tag entity to database, by creating it with its constructor
     * 
     * @param tagName
     * @return
     */
    public static Tag addTag(String tagName)
    {
	Tag tag = new Tag(tagName);
	dao.put(tag);
	return tag;
    }

    @Override
    public String toString()
    {
	return "id: " + tag;
    }
}
