package com.agilecrm.user.access;

public enum AdminPanelAccessScopes {
	ADD_AFFILIATE_AMOUNT,LOGIN_INTO_DOMAIN,REFUND_AMOUNT,DELETE_USER,CANCEL_PLAN,CANCEL_SUBPLAN,DELETE_ACCOUNT,
	ADD_USER,SHOW_USERS,AFFILIATES,ACCOUNT_RELEASE,VIEW_LOGS;
}
