package com.agilecrm.user.access;

public enum AdminPanelAccessScopes {
	LOGIN_INTO_DOMAIN,REFUND_AMOUNT,DELETE_USER,CHANGE_PLAN,CANCEL_SUBSCRIPTION,DELETE_ACCOUNT,
	ADD_USER,SHOW_USERS,AFFILIATES,ACCOUNT_RELEASE,VIEW_LOGS;
}
