package com.campaignio.twitter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.Id;

import org.json.JSONObject;

import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterFactory;
import twitter4j.auth.AccessToken;

import com.agilecrm.db.ObjectifyGenericDao;
import com.agilecrm.util.DBUtil;
import com.campaignio.logger.util.LogUtil;

/**
 * 
 * <code>TwitterJob</code> is the base class to post status in twitter.Token and
 * token secret are generated when the user logs into twitter using this
 * app.Using those token and token secret twitterjob posts status in twitter.
 * 
 * @author Manohar
 * 
 */
class TwitterJob
{

    // Constants
    /**
     * Consumer Key
     */
    static final String CONSUMER_KEY = "PtWo0H7yLiEZv46r3FDJbw";
    /**
     * Consumer secret
     */
    static final String CONSUMER_SECRET = "kntZFSrFVGogu9DF6OszABqm6N3eQcprN2QT3bm3S8";

    // Online, Offline or Unknown
    /**
     * Token generated by twitter
     */
    public String token;
    /**
     * Token secret generated by twitter
     */
    public String token_secret;
    /**
     * Tweet to be posted
     */
    public String status;
    /**
     * Contact id that subscribes to campaign
     */
    public String subscriber_id;
    /**
     * Campaign Id
     */
    public String campaign_id;

    /**
     * Constructs a new {@link TwitterJob}
     * 
     * @param token
     *            Token generated by twitter
     * @param tokenSecret
     *            Token secret generated by twitter
     * @param status
     *            Tweet to be posted
     * @param subscriberId
     *            Contact id that subscribes to campaign
     * @param campaignId
     *            Campaign Id
     */
    TwitterJob(String token, String tokenSecret, String status,
	    String subscriberId, String campaignId)
    {
	this.token = token;
	this.token_secret = tokenSecret;
	this.status = status;
	this.subscriber_id = subscriberId;
	this.campaign_id = campaignId;
    }

    /**
     * Post tweet in the twitter
     * 
     * @return Boolean value-true if tweet posted successfully otherwise false
     */
    public boolean postStatus()
    {
	try
	{

	    Twitter twitter = new TwitterFactory().getInstance();
	    twitter.setOAuthConsumer(CONSUMER_KEY, CONSUMER_SECRET);

	    AccessToken accessToken = new AccessToken(token, token_secret);
	    twitter.setOAuthAccessToken(accessToken);

	    // System.out.println("Twitter Screename " +
	    // twitter.getScreenName());

	    Status status = twitter.updateStatus(token_secret);
	    LogUtil.addLogFromID(
		    campaign_id,
		    subscriber_id,
		    "Twitter - Successfully updated the status to ["
			    + status.getText() + "].");

	    return true;

	}
	catch (Exception e)
	{
	    LogUtil.addLogFromID(campaign_id, campaign_id,
		    "Tweeting failed " + e.getMessage());
	    return false;
	}
    }

}

/**
 * <code>TwitterQueue</code> is responsible to post tweets at regular intervals
 * set by user.
 * 
 * @author Manohar
 * 
 */
public class TwitterQueue
{

    // Key
    /**
     * TwitterQueue Id
     */
    @Id
    public Long id;

    // Queue
    /**
     * List of Twitter Jobs
     */
    public List<TwitterJob> twitter_jobs = new ArrayList<TwitterJob>();

    // Twitter Account
    /**
     * Twitter Account
     */
    public String account;

    // Rate Limit
    /**
     * Rate limit
     */
    public String rate_limit;

    /**
     * 5 tweets per hour
     */
    public static final String TWITTER_DB_RATE_LIMIT_HOURLY_5 = "rate_limit_5";
    /**
     * 10 tweets per hour
     */
    public static final String TWITTER_DB_RATE_LIMIT_HOURLY_10 = "rate_limit_10";
    /**
     * 20 tweets per hour
     */
    public static final String TWITTER_DB_RATE_LIMIT_HOURLY_20 = "rate_limit_20";

    // Dao
    /**
     * Dao for TwitterQueue class
     */
    private static ObjectifyGenericDao<TwitterQueue> dao = new ObjectifyGenericDao<TwitterQueue>(
	    TwitterQueue.class);

    /**
     * Default TwitterQueue
     */
    TwitterQueue()
    {

    }

    /**
     * Twitter Queue with account and ratelimit
     * 
     * @param account
     *            Twitter account
     * @param rateLimit
     *            Rate Limit
     */
    TwitterQueue(String account, String rateLimit)
    {
	this.account = account;
	this.rate_limit = rateLimit;

    }

    /**
     * Add twitter jobs to twitter queue to post tweets at regular intervals
     * 
     * @param account
     *            Twitter account
     * @param token
     *            Token generated by twitter
     * @param tokenSecret
     *            Token secret generated by twitter
     * @param message
     *            Tweet to be posted
     * @param rateLimit
     *            Number of tweets per hour
     * @param subscriberJSON
     *            Contact data that subscribes to campaign
     * @param campaignJSON
     *            Campaign data
     * @return true if successfully added to queue otherwise false
     */
    public static boolean addToTwitterQueue(String account, String token,
	    String tokenSecret, String message, String rateLimit,
	    JSONObject subscriberJSON, JSONObject campaignJSON)
    {

	// Add to Twitter Queue
	try
	{
	    // Get Existing Queue
	    TwitterQueue twitterQueue = getTwitterQueueForAccount(account,
		    rateLimit);
	    if (twitterQueue == null)
	    {
		twitterQueue = new TwitterQueue(account, rateLimit);
	    }

	    // Add to Old JSONArray
	    String campaignId = DBUtil.getId(campaignJSON);
	    String subscriberId = DBUtil.getId(subscriberJSON);
	    TwitterJob twitterJob = new TwitterJob(token, tokenSecret, message,
		    subscriberId, campaignId);
	    twitterQueue.twitter_jobs.add(twitterJob);

	    return true;

	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}

	return false;

    }

    /**
     * Gets TwitterQueue for an account
     * 
     * @param account
     *            Twitter account
     * @param rateLimit
     *            Number of tweets per hour
     * @return resultant twitter Queue
     */
    public static TwitterQueue getTwitterQueueForAccount(String account,
	    String rateLimit)
    {
	Map<String, Object> searchMap = new HashMap<String, Object>();
	searchMap.put("account", account);
	searchMap.put("rate_limit", rateLimit);

	return dao.getByProperty(searchMap);
    }

    /**
     * Gets list of twitter Queues with respect to rate limit
     * 
     * @param rateLimit
     *            Tweets limit per hour
     * @return list of twitter queues
     */
    public static List<TwitterQueue> getTwitterQueue(String rateLimit)
    {

	return dao.listByProperty("rate_limit", rateLimit);
    }

    /**
     * Runs Twitter Queues having specified rate-limit
     * 
     * @param rateLimit
     *            Number of tweets per hour
     */
    public static void runTwitterQueues(String rateLimit)
    {
	// Get All Queues for specified RateLimit
	List<TwitterQueue> twitterQueues = getTwitterQueue(rateLimit);

	System.out.println("Tweeting " + twitterQueues.size());

	for (TwitterQueue twitterQueue : twitterQueues)
	{
	    try
	    {

		List<TwitterJob> twitterJobs = twitterQueue.twitter_jobs;

		System.out.println("Queue " + twitterJobs.size());

		// Get First Job, Execute it
		if (twitterJobs.size() > 0)
		{

		    try
		    {
			twitterJobs.get(0).postStatus();
		    }
		    catch (Exception e)
		    {
			e.printStackTrace();
		    }

		    twitterJobs.remove(0);

		    // Delete the queue for that account if no more jobs are
		    // pending
		    if (twitterJobs.size() == 0)
			twitterQueue.delete();
		    else
		    {
			twitterQueue.twitter_jobs = twitterJobs;
			twitterQueue.save();
		    }
		}

	    }
	    catch (Exception e)
	    {
		e.printStackTrace();
	    }
	}
    }

    /**
     * Saves TwitterQueue
     */
    public void save()
    {
	dao.put(this);
    }

    /**
     * Deletes TwitterQueue
     */
    public void delete()
    {
	dao.delete(this);
    }

}
