{
    "name": "Wait",
    "thumbnail": "json/nodes/images/common/wait.png",
    "icon": "json/nodes/icons/common/wait.png",
    "info": "Wait for a specified duration before next action. Useful for responders and periodic emails.",
    "help": "Wait for a specified duration before next action. Useful for responders and periodic emails.",
    "author": "John",
    "company": "mantra",
    "language": "en",
    "branches": "yes",
    "workflow_tasklet_class_name": "com.campaignio.tasklets.agile.Wait",
    "category": "Utilities",
    "ui": [{
			"label": " Duration",
			"required": "required",
            "category": "Info",
			"name": "duration",
            "id":"duration",
			"title": "Enter the duration period.",
			"fieldType": "input",
            "type": "number",
            "min" : "1"
    },{   
			"label": "Type",
           "required": "required",
            "category": "Info",
            "name": "duration_type",
            "id": "duration_type",
            "title": "Select the type of duration.",
            "options": {"Days":"days",
            			"Business Days":"business_days",
				        "Hours":"hours",
				        "Minutes":"mins"
			          },
			"fieldType": "select",
			"type": "select" 
         },
         
        	 {

             "label": "Time zone",
             "required": "No",
             "category": "Settings",
 			"value": "(GMT-06:00 ) Central Time (US & Canada)",
             "name": "timezone",
             "title": "Select the time zone of your location.",
              "options": {
            	"Select time zone for Business days":"empty_timezone" , 
                "(GMT-12:00) International Date Line West" : "(GMT-12:00 ) International Date Line West", 
                "(GMT-11:00) Midway Island, Samoa" : "(GMT-11:00 ) Midway Island, Samoa",
                "(GMT-10:00) Hawaii" : "(GMT-10:00 ) Hawaii",
                "(GMT-09:00) Alaska" :"(GMT-09:00 ) Alaska",
                "(GMT-08:00) Tijuana, Baja California" : "(GMT-08:00 ) Tijuana, Baja California" ,
                "(GMT-08:00) Pacific Time (US & Canada)" : "(GMT-08:00 ) Pacific Time (US and Canada)",
                "(GMT-07:00) Mountain Time (US & Canada)" : "(GMT-07:00 ) Mountain Time (US and Canada)",
                "(GMT-07:00) Chihuahua, La Paz, Mazatlan" :"(GMT-07:00 ) Chihuahua, La Paz, Mazatlan",
                "(GMT-07:00) Arizona" : "(GMT-07:00 ) Arizona",
                "(GMT-06:00) Saskatchewan" : "(GMT-06:00 ) Saskatchewan",
                "(GMT-06:00) Guadalajara, Mexico City, Monterrey" : "(GMT-06:00 ) Guadalajara, Mexico City, Monterrey",
                "(GMT-06:00) Central Time (US & Canada)" : "(GMT-06:00 ) Central Time (US and Canada)",
                "(GMT-06:00) Central America" : "(GMT-06:00 ) Central America",
                "(GMT-05:00) Indiana (East)" : "(GMT-05:00 ) Indiana (East)",
                "(GMT-05:00) Eastern Time (US & Canada)" : "(GMT-05:00 ) Eastern Time (US and Canada)",
                "(GMT-05:00) Bogota, Lima, Quito, Rio Branco" : "(GMT-05:00 ) Bogota, Lima, Quito, Rio Branco",
                "(GMT-04:30) Caracas" : "(GMT-04:30 ) Caracas" , 
                "(GMT-04:00) Santiago" :  "(GMT-04:00 ) Santiago",
                "(GMT-04:00) Manaus" : "(GMT-04:00 ) Manaus",
                "(GMT-04:00) La Paz" : "(GMT-04:00 ) La Paz" ,
                "(GMT-04:00) Atlantic Time (Canada)" :  "(GMT-04:00 ) Atlantic Time (Canada)" ,
                "(GMT-03:30) Newfoundland" :  "(GMT-03:30 ) Newfoundland",
                "(GMT-03:00) Montevideo" :  "(GMT-03:00 ) Montevideo",
                "(GMT-03:00) Greenland" :  "(GMT-03:00 ) Greenland",
                "(GMT-03:00) Georgetown" : "(GMT-03:00 ) Georgetown" ,
                "(GMT-03:00) Buenos Aires" : "(GMT-03:00 ) Buenos Aires",
                "(GMT-03:00) Brasilia" : "(GMT-03:00 ) Brasilia",
                "(GMT-02:00) Mid-Atlantic" :  "(GMT-02:00 ) Mid-Atlantic",
                "(GMT-01:00) Cape Verde Is." : "(GMT-01:00 ) Cape Verde Is.",
                "(GMT-01:00) Azores" : "(GMT-01:00 ) Azores",
                "(GMT) Casablanca" : "(GMT+00:00 ) Casablanca",
                "(GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London" : "(GMT+00:00 ) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London",
                "(GMT) Monrovia, Reykjavik" :  "(GMT+00:00 ) Monrovia, Reykjavik",
                "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna": "(GMT+01:00 ) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
                "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague" :  "(GMT+01:00 ) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
                "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris" :  "(GMT+01:00 ) Brussels, Copenhagen, Madrid, Paris",
                "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb" :   "(GMT+01:00 ) Sarajevo, Skopje, Warsaw, Zagreb",
                "(GMT+01:00) West Central Africa" :   "(GMT+01:00 ) West Central Africa",
                "(GMT+02:00) Amman" :  "(GMT+02:00 ) Amman",
                "(GMT+02:00) Athens, Bucharest, Istanbul" :  "(GMT+02:00 ) Athens, Bucharest, Istanbul",
                "(GMT+02:00) Beirut" : "(GMT+02:00 ) Beirut",
                "(GMT+02:00) Cairo" :  "(GMT+02:00 ) Cairo",
                "(GMT+02:00) Harare, Pretoria" : "(GMT+02:00 ) Harare, Pretoria",
                "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" :  "(GMT+02:00 ) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
                "(GMT+02:00) Jerusalem" : "(GMT+02:00 ) Jerusalem",
                "(GMT+02:00) Minsk" : "(GMT+02:00 ) Minsk",
                "(GMT+02:00) Windhoek" : "(GMT+02:00 ) Windhoek",
                "(GMT+03:00) Baghdad" :  "(GMT+03:00 ) Baghdad",
                "(GMT+03:00) Kuwait, Riyadh" :  "(GMT+03:00 ) Kuwait, Riyadh",
                "(GMT+03:00) Nairobi" :  "(GMT+03:00 ) Nairobi",
                "(GMT+03:00) Tbilisi": "(GMT+03:00 ) Tbilisi",
                "(GMT+03:30) Tehran": "(GMT+03:30 ) Tehran",
                "(GMT+04:00) Abu Dhabi, Muscat":  "(GMT+04:00 ) Abu Dhabi, Muscat",
                "(GMT+04:00) Baku" :  "(GMT+04:00 ) Baku",
                "(GMT+04:00) Port Louis" :  "(GMT+04:00 ) Port Louis",
                "(GMT+04:00) Yerevan":  "(GMT+04:00 ) Yerevan",
                "(GMT+04:30) Kabul":  "(GMT+04:30 ) Kabul",
                "(GMT+05:00) Ekaterinburg" :  "(GMT+05:00 ) Ekaterinburg",
                "(GMT+05:00) Islamabad, Karachi" :  "(GMT+05:00 ) Islamabad, Karachi",
                "(GMT+05:00) Tashkent" :  "(GMT+05:00 ) Tashkent",
                "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi": "(GMT+05:30 ) Chennai, Kolkata, Mumbai, New Delhi",
                "(GMT+05:30) Sri Jayawardenepura":   "(GMT+05:30 ) Sri Jayawardenepura",
                "(GMT+05:45) Kathmandu" : "(GMT+05:45 ) Kathmandu",
                "(GMT+06:00) Almaty, Novosibirsk" :  "(GMT+06:00 ) Almaty, Novosibirsk",
                "(GMT+06:00) Astana, Dhaka" :  "(GMT+06:00 ) Astana, Dhaka",
                "(GMT+06:30) Yangon (Rangoon)" :  "(GMT+06:30 ) Yangon (Rangoon)",
                "(GMT+07:00) Bangkok, Hanoi, Jakarta" :  "(GMT+07:00 ) Bangkok, Hanoi, Jakarta",
                "(GMT+07:00) Krasnoyarsk" :  "(GMT+07:00 ) Krasnoyarsk",
                "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi" :  "(GMT+08:00 ) Beijing, Chongqing, Hong Kong, Urumqi",
                "(GMT+08:00) Irkutsk, Ulaan Bataar" :  "(GMT+08:00 ) Irkutsk, Ulaan Bataar",
                "(GMT+08:00) Kuala Lumpur, Singapore" :  "(GMT+08:00 ) Kuala Lumpur, Singapore",
                "(GMT+08:00) Perth" :  "(GMT+08:00 ) Perth",
                "(GMT+08:00) Taipei" : "(GMT+08:00 ) Taipei" ,
                "(GMT+09:00) Osaka, Sapporo, Tokyo" : "(GMT+09:00 ) Osaka, Sapporo, Tokyo",
                "(GMT+09:00) Seoul" : "(GMT+09:00 ) Seoul",
                "(GMT+09:00) Yakutsk" :  "(GMT+09:00 ) Yakutsk",
                "(GMT+09:30) Adelaide" :  "(GMT+09:30 ) Adelaide",
                "(GMT+09:30) Darwin" :  "(GMT+09:30 ) Darwin",
                "(GMT+10:00) Canberra, Melbourne, Sydney" :  "(GMT+10:00 ) Canberra, Melbourne, Sydney",
                "(GMT+10:00) Guam, Port Moresby" :  "(GMT+10:00 ) Guam, Port Moresby",
                "(GMT+10:00) Hobart" : "(GMT+10:00 ) Hobart",
                "(GMT+10:00) Vladivostok" : "(GMT+10:00 ) Vladivostok",
                "(GMT+11:00) Magadan, Solomon Is., New Caledonia" : "(GMT+11:00 ) Magadan, Solomon Is., New Caledonia",
                "(GMT+12:00) Auckland, Wellington" :  "(GMT+12:00 ) Auckland, Wellington",
                "(GMT+12:00) Fiji, Kamchatka, Marshall Is." :  "(GMT+12:00 ) Fiji, Kamchatka, Marshall Is.",
                "(GMT+13:00) Nuku alofa" :  "(GMT+13:00 ) Nuku alofa" 
             },
             "fieldType": "select",
             "type": "select" 
        	 },{

                 "label": "Time",
                 "required": "required",
                 "category": "Settings",
                 "name": "at",
                 "id": "at",
                 "multiple": "multiple",
                 "ismultiple": "true",
                 "title": "Select the time ",
                 "options": {
                	 "Any time":"any_time",
                 	"9:00 AM": "09:00",
                     "9:30 AM": "09:30",
                     "10:00 AM": "10:00",
                     "10:30 AM": "10:30",
                     "11:00 AM": "11:00",
                     "11:30 AM": "11:30",
                     "12:00 PM": "12:00",
                     "12:30 PM": "12:30",
                     "1:00 PM": "13:00",
                     "1:30 PM": "13:30",
                     "2:00 PM": "14:00",
                     "2:30 PM": "14:30",
                     "3:00 PM": "15:00",
                     "3:30 PM": "15:30",
                     "4:00 PM": "16:00",
                     "4:30 PM": "16:30",
                     "5:00 PM": "17:00",
                     "5:30 PM": "17:30",
                     "6:00 PM": "18:00",
                     "6:30 PM": "18:30",
                     "7:00 PM": "19:00",
                     "7:30 PM": "19:30",
                     "8:00 PM": "20:00",
                     "8:30 PM": "20:30",
                     "9:00 PM": "21:00",
                     "9:30 PM": "21:30",
                     "10:00 PM": "22:00",
                     "10:30 PM": "22:30",
                     "11:00 PM": "23:00",
                     "11:30 PM": "23:30",
                     "12:00 AM": "00:01",
                     "12:30 AM": "00:30",
                     "1:00 AM": "01:00",
                     "1:30 AM": "01:30",
                     "2:00 AM": "02:00",
                     "2:30 AM": "02:30",
                     "3:00 AM": "03:00",
                     "3:30 AM": "03:30",
                     "4:00 AM": "04:00",
                     "4:30 AM": "04:30",
                     "5:00 AM": "05:00",
                     "5:30 AM": "05:30",
                     "6:00 AM": "06:00",
                     "6:30 AM": "06:30",
                     "7:00 AM": "07:00",
                     "7:30 AM": "07:30",
                     "8:00 AM": "08:00",
                     "8:30 AM": "08:30"
                 },
                 "fieldType": "select",
                 "type": "select" 
             
        	 }
         ,{
            "label": "Wait for a specified duration before proceeding to the next step.<br/>For example, send email-1, wait for 2 days and then send email-2.",
            "category": "Help",
            "fieldType": "label",
            "type": "label" 
        } 
    ]
}