{
    "nodes": [
        {
            "NodeDefinition": {
                "name": "Start",
                "thumbnail": "json/nodes/images/common/Start.png",
                "icon": "json/nodes/icons/common/Start.png",
                "info": "Entry point of your campaign. Please create workflow for your campaign starting from here.",
                "help": "Start point in your campaign workflow.",
                "author": "John",
                "company": "Invox",
                "language": "en",
                "branches": "start",
                "workflow_tasklet_class_name": "com.campaignio.tasklets.agile.Start",
                "category": "Basic",
                "ui": [
                    {
                        "label": "Entry point of your campaign. Please create workflow for your campaign starting from here.",
                        "category": "Help",
                        "componet": "label",
                        "type": "label"
                    }
                ]
            },
            "id": "PBXNODE1",
            "xPosition": 500,
            "yPosition": 10,
            "displayname": "Start",
            "JsonValues": [],
            "States": [
                {
                    "start": "PBXHWo1PHDnoJ"
                }
            ]
        },
        {
            "NodeDefinition": {
                "ui": [
                    {
                        "id": "from_name",
                        "title": "Enter your name.",
                        "category": "Info",
                        "fieldType": "input",
                        "name": "from_name",
                        "label": "From (Name):",
                        "type": "text",
                        "required": "required"
                    },
                    {
                        "id": "from_email",
                        "title": "Enter your email address.",
                        "category": "Info",
                        "fieldType": "input",
                        "name": "from_email",
                        "label": "From (Email):",
                        "type": "email",
                        "required": "required"
                    },
                    {
                        "id": "to_email",
                        "title": "Enter your subscriber E-mail ID. If you are using a list, you can use {{email}}",
                        "category": "Info",
                        "fieldType": "input",
                        "name": "to_email",
                        "value": "{{email}}",
                        "label": "To",
                        "type": "email",
                        "required": "required"
                    },
                    {
                        "id": "cc_email",
                        "title": "Enter CC email address",
                        "category": "Info",
                        "fieldType": "input",
                        "name": "cc_email",
                        "label": "CC",
                        "type": "email"
                    },
                    {
                        "id": "subject",
                        "title": "Enter your subject for your email.",
                        "category": "Info",
                        "fieldType": "input",
                        "name": "subject",
                        "label": "Subject",
                        "type": "text",
                        "required": "required"
                    },
                    {
                        "id": "replyto_email",
                        "title": "Enter email your subscribers need to reply.",
                        "category": "Info",
                        "fieldType": "input",
                        "name": "replyto_email",
                        "label": "Reply To",
                        "type": "email"
                    },
                    {
                        "id": "merge_fields",
                        "title": "Select required merge field to insert into below Text Field.",
                        "category": "Text",
                        "fieldType": "merge_fields",
                        "name": "merge_fields",
                        "label": "",
                        "type": "select",
                        "target_type": "text_email"
                    },
                    {
                        "id": "text_email",
                        "cols": "75",
                        "title": "Enter text content here.",
                        "category": "Text",
                        "fieldType": "textarea",
                        "name": "text_email",
                        "label": "Text",
                        "type": "textarea",
                        "required": "required",
                        "rows": "13"
                    },
                    {
                        "id": "merge_fields",
                        "title": "Select required merge field to insert into below HTML Field.",
                        "category": "HTML",
                        "fieldType": "merge_fields",
                        "name": "merge_fields",
                        "label": "",
                        "type": "select",
                        "target_type": "tinyMCEhtml_email"
                    },
                    {
                        "id": "html_email",
                        "title": "Enter Your HTML message.",
                        "category": "HTML",
                        "fieldType": "html",
                        "name": "html_email",
                        "label": "HTML Editor",
                        "type": "html"
                    },
                    {
                        "title": "AgileCRM will track your Clicks.",
                        "category": "Settings",
                        "fieldType": "select",
                        "name": "track_clicks",
                        "label": "Track Clicks:",
                        "type": "select",
                        "required": "No",
                        "options": {
                            "*No": "no",
                            "Yes": "yes"
                        }
                    },
                    {
                        "id": "purl_keyword",
                        "title": "While tracking clicks, AgileCRM can show a keyword in the URL. Valid only when you are tracking clicks.",
                        "category": "Settings",
                        "fieldType": "input",
                        "name": "purl_keyword",
                        "label": "Purl Keyword:",
                        "type": "text"
                    },
                    {
                        "label": "Simply choose timezone, day and time. Agile can schedule your email delivery."
                    },
                    {
                        "title": "Select the time zone for your email delivery.",
                        "category": "Settings",
                        "fieldType": "select",
                        "name": "time_zone",
                        "value": "(GMT-06:00) Central Time (US & Canada)",
                        "label": "Time zone",
                        "type": "select",
                        "required": "No",
                        "options": {
                            "Europe/Sofia": "Europe/Sofia",
                            "Africa/Douala": "Africa/Douala",
                            "Atlantic/Jan_Mayen": "Atlantic/Jan_Mayen",
                            "America/Catamarca": "America/Catamarca",
                            "America/Dawson": "America/Dawson",
                            "US/East-Indiana": "US/East-Indiana",
                            "Asia/Bangkok": "Asia/Bangkok",
                            "Asia/Yerevan": "Asia/Yerevan",
                            "America/Bogota": "America/Bogota",
                            "Asia/Colombo": "Asia/Colombo",
                            "BST": "BST",
                            "Africa/Kampala": "Africa/Kampala",
                            "Africa/Blantyre": "Africa/Blantyre",
                            "Europe/Volgograd": "Europe/Volgograd",
                            "Australia/Victoria": "Australia/Victoria",
                            "ROK": "ROK",
                            "Atlantic/St_Helena": "Atlantic/St_Helena",
                            "Europe/Mariehamn": "Europe/Mariehamn",
                            "Africa/Malabo": "Africa/Malabo",
                            "Asia/Nicosia": "Asia/Nicosia",
                            "Universal": "Universal",
                            "Asia/Katmandu": "Asia/Katmandu",
                            "America/Resolute": "America/Resolute",
                            "America/Danmarkshavn": "America/Danmarkshavn",
                            "SystemV/EST5": "SystemV/EST5",
                            "America/Regina": "America/Regina",
                            "America/Anguilla": "America/Anguilla",
                            "Asia/Amman": "Asia/Amman",
                            "Europe/Brussels": "Europe/Brussels",
                            "Europe/Simferopol": "Europe/Simferopol",
                            "America/Argentina/Ushuaia": "America/Argentina/Ushuaia",
                            "America/North_Dakota/Center": "America/North_Dakota/Center",
                            "SystemV/PST8PDT": "SystemV/PST8PDT",
                            "Indian/Kerguelen": "Indian/Kerguelen",
                            "Pacific/Chuuk": "Pacific/Chuuk",
                            "Europe/Istanbul": "Europe/Istanbul",
                            "Etc/UTC": "Etc/UTC",
                            "Pacific/Rarotonga": "Pacific/Rarotonga",
                            "America/Bahia_Banderas": "America/Bahia_Banderas",
                            "GB": "GB",
                            "Asia/Hebron": "Asia/Hebron",
                            "Australia/Broken_Hill": "Australia/Broken_Hill",
                            "PST8PDT": "PST8PDT",
                            "Antarctica/Casey": "Antarctica/Casey",
                            "Pacific/Ponape": "Pacific/Ponape",
                            "Europe/Stockholm": "Europe/Stockholm",
                            "Africa/Bamako": "Africa/Bamako",
                            "ART": "ART",
                            "Africa/Asmera": "Africa/Asmera",
                            "America/St_Johns": "America/St_Johns",
                            "Antarctica/South_Pole": "Antarctica/South_Pole",
                            "Africa/Dar_es_Salaam": "Africa/Dar_es_Salaam",
                            "America/Virgin": "America/Virgin",
                            "Asia/Novosibirsk": "Asia/Novosibirsk",
                            "America/Argentina/Tucuman": "America/Argentina/Tucuman",
                            "Asia/Sakhalin": "Asia/Sakhalin",
                            "Europe/Budapest": "Europe/Budapest",
                            "America/Curacao": "America/Curacao",
                            "Africa/Tunis": "Africa/Tunis",
                            "Pacific/Guam": "Pacific/Guam",
                            "America/Fort_Wayne": "America/Fort_Wayne",
                            "Africa/Maseru": "Africa/Maseru",
                            "Africa/Asmara": "Africa/Asmara",
                            "America/Asuncion": "America/Asuncion",
                            "America/Indiana/Winamac": "America/Indiana/Winamac",
                            "Europe/Vaduz": "Europe/Vaduz",
                            "Asia/Ulaanbaatar": "Asia/Ulaanbaatar",
                            "Asia/Vientiane": "Asia/Vientiane",
                            "Africa/Niamey": "Africa/Niamey",
                            "America/Thunder_Bay": "America/Thunder_Bay",
                            "Asia/Brunei": "Asia/Brunei",
                            "US/Samoa": "US/Samoa",
                            "Africa/Djibouti": "Africa/Djibouti",
                            "Asia/Tbilisi": "Asia/Tbilisi",
                            "America/Merida": "America/Merida",
                            "America/Recife": "America/Recife",
                            "Indian/Reunion": "Indian/Reunion",
                            "AST": "AST",
                            "NZ-CHAT": "NZ-CHAT",
                            "JST": "JST",
                            "Canada/East-Saskatchewan": "Canada/East-Saskatchewan",
                            "CTT": "CTT",
                            "Asia/Oral": "Asia/Oral",
                            "SystemV/MST7": "SystemV/MST7",
                            "Africa/Lusaka": "Africa/Lusaka",
                            "America/Tortola": "America/Tortola",
                            "Africa/Ouagadougou": "Africa/Ouagadougou",
                            "Asia/Kuching": "Asia/Kuching",
                            "America/Tegucigalpa": "America/Tegucigalpa",
                            "Asia/Novokuznetsk": "Asia/Novokuznetsk",
                            "Europe/Vilnius": "Europe/Vilnius",
                            "Asia/Bishkek": "Asia/Bishkek",
                            "Navajo": "Navajo",
                            "America/Moncton": "America/Moncton",
                            "America/Maceio": "America/Maceio",
                            "Africa/Dakar": "Africa/Dakar",
                            "GB-Eire": "GB-Eire",
                            "America/Belize": "America/Belize",
                            "Etc/GMT": "Etc/GMT",
                            "America/Cuiaba": "America/Cuiaba",
                            "Asia/Tashkent": "Asia/Tashkent",
                            "Atlantic/Canary": "Atlantic/Canary",
                            "US/Pacific": "US/Pacific",
                            "America/Rankin_Inlet": "America/Rankin_Inlet",
                            "Asia/Jerusalem": "Asia/Jerusalem",
                            "Antarctica/Rothera": "Antarctica/Rothera",
                            "Australia/Queensland": "Australia/Queensland",
                            "Australia/West": "Australia/West",
                            "Indian/Cocos": "Indian/Cocos",
                            "America/Glace_Bay": "America/Glace_Bay",
                            "Atlantic/Cape_Verde": "Atlantic/Cape_Verde",
                            "America/Cambridge_Bay": "America/Cambridge_Bay",
                            "Indian/Mauritius": "Indian/Mauritius",
                            "Etc/GMT-14": "Etc/GMT-14",
                            "Etc/GMT-13": "Etc/GMT-13",
                            "Australia/Brisbane": "Australia/Brisbane",
                            "Etc/GMT-12": "Etc/GMT-12",
                            "Etc/GMT-11": "Etc/GMT-11",
                            "Etc/GMT-10": "Etc/GMT-10",
                            "America/Grenada": "America/Grenada",
                            "SystemV/MST7MDT": "SystemV/MST7MDT",
                            "Europe/Busingen": "Europe/Busingen",
                            "Antarctica/Vostok": "Antarctica/Vostok",
                            "Arctic/Longyearbyen": "Arctic/Longyearbyen",
                            "Etc/GMT+11": "Etc/GMT+11",
                            "Pacific/Auckland": "Pacific/Auckland",
                            "Etc/GMT+12": "Etc/GMT+12",
                            "America/Argentina/ComodRivadavia": "America/Argentina/ComodRivadavia",
                            "Antarctica/DumontDUrville": "Antarctica/DumontDUrville",
                            "Etc/GMT+10": "Etc/GMT+10",
                            "Australia/Yancowinna": "Australia/Yancowinna",
                            "Africa/Nairobi": "Africa/Nairobi",
                            "Pacific/Norfolk": "Pacific/Norfolk",
                            "Greenwich": "Greenwich",
                            "SystemV/YST9": "SystemV/YST9",
                            "Europe/Paris": "Europe/Paris",
                            "Asia/Irkutsk": "Asia/Irkutsk",
                            "Pacific/Apia": "Pacific/Apia",
                            "Pacific/Chatham": "Pacific/Chatham",
                            "America/Caracas": "America/Caracas",
                            "Europe/Sarajevo": "Europe/Sarajevo",
                            "Africa/Maputo": "Africa/Maputo",
                            "America/Metlakatla": "America/Metlakatla",
                            "Brazil/Acre": "Brazil/Acre",
                            "Atlantic/South_Georgia": "Atlantic/South_Georgia",
                            "Asia/Baghdad": "Asia/Baghdad",
                            "US/Aleutian": "US/Aleutian",
                            "Pacific/Saipan": "Pacific/Saipan",
                            "Asia/Dhaka": "Asia/Dhaka",
                            "PLT": "PLT",
                            "Africa/Cairo": "Africa/Cairo",
                            "Asia/Istanbul": "Asia/Istanbul",
                            "Asia/Singapore": "Asia/Singapore",
                            "Europe/Belgrade": "Europe/Belgrade",
                            "Europe/Moscow": "Europe/Moscow",
                            "Portugal": "Portugal",
                            "Pacific/Funafuti": "Pacific/Funafuti",
                            "America/Inuvik": "America/Inuvik",
                            "Africa/Bissau": "Africa/Bissau",
                            "Asia/Taipei": "Asia/Taipei",
                            "Atlantic/Faroe": "Atlantic/Faroe",
                            "Pacific/Majuro": "Pacific/Majuro",
                            "America/Argentina/Catamarca": "America/Argentina/Catamarca",
                            "Canada/Pacific": "Canada/Pacific",
                            "EET": "EET",
                            "SystemV/HST10": "SystemV/HST10",
                            "Indian/Comoro": "Indian/Comoro",
                            "America/Rosario": "America/Rosario",
                            "SystemV/AST4ADT": "SystemV/AST4ADT",
                            "America/Manaus": "America/Manaus",
                            "Asia/Shanghai": "Asia/Shanghai",
                            "America/Indiana/Vevay": "America/Indiana/Vevay",
                            "Australia/Hobart": "Australia/Hobart",
                            "Asia/Dili": "Asia/Dili",
                            "America/Indiana/Marengo": "America/Indiana/Marengo",
                            "Asia/Aqtobe": "Asia/Aqtobe",
                            "Australia/Sydney": "Australia/Sydney",
                            "Indian/Chagos": "Indian/Chagos",
                            "America/Phoenix": "America/Phoenix",
                            "Europe/Luxembourg": "Europe/Luxembourg",
                            "Turkey": "Turkey",
                            "Asia/Makassar": "Asia/Makassar",
                            "Asia/Phnom_Penh": "Asia/Phnom_Penh",
                            "Mexico/BajaNorte": "Mexico/BajaNorte",
                            "Australia/Currie": "Australia/Currie",
                            "America/Argentina/Cordoba": "America/Argentina/Cordoba",
                            "America/Cancun": "America/Cancun",
                            "Asia/Baku": "Asia/Baku",
                            "IET": "IET",
                            "WET": "WET",
                            "Asia/Seoul": "Asia/Seoul",
                            "America/Porto_Acre": "America/Porto_Acre",
                            "Antarctica/McMurdo": "Antarctica/McMurdo",
                            "Europe/Rome": "Europe/Rome",
                            "America/Lima": "America/Lima",
                            "Atlantic/Stanley": "Atlantic/Stanley",
                            "NZ": "NZ",
                            "America/Dawson_Creek": "America/Dawson_Creek",
                            "Europe/Helsinki": "Europe/Helsinki",
                            "Asia/Anadyr": "Asia/Anadyr",
                            "America/Matamoros": "America/Matamoros",
                            "America/Argentina/San_Juan": "America/Argentina/San_Juan",
                            "America/Denver": "America/Denver",
                            "America/Coral_Harbour": "America/Coral_Harbour",
                            "Australia/Eucla": "Australia/Eucla",
                            "US/Michigan": "US/Michigan",
                            "SystemV/AST4": "SystemV/AST4",
                            "America/Cordoba": "America/Cordoba",
                            "Brazil/East": "Brazil/East",
                            "America/Detroit": "America/Detroit",
                            "America/Indiana/Tell_City": "America/Indiana/Tell_City",
                            "America/Campo_Grande": "America/Campo_Grande",
                            "America/Hermosillo": "America/Hermosillo",
                            "America/Boise": "America/Boise",
                            "America/Whitehorse": "America/Whitehorse",
                            "America/St_Kitts": "America/St_Kitts",
                            "Europe/Guernsey": "Europe/Guernsey",
                            "UCT": "UCT",
                            "America/Pangnirtung": "America/Pangnirtung",
                            "MET": "MET",
                            "Asia/Tehran": "Asia/Tehran",
                            "Eire": "Eire",
                            "America/Santa_Isabel": "America/Santa_Isabel",
                            "Asia/Almaty": "Asia/Almaty",
                            "Asia/Dacca": "Asia/Dacca",
                            "America/Chicago": "America/Chicago",
                            "Asia/Ho_Chi_Minh": "Asia/Ho_Chi_Minh",
                            "America/Boa_Vista": "America/Boa_Vista",
                            "Poland": "Poland",
                            "America/Mazatlan": "America/Mazatlan",
                            "America/Indiana/Petersburg": "America/Indiana/Petersburg",
                            "America/Iqaluit": "America/Iqaluit",
                            "Africa/Algiers": "Africa/Algiers",
                            "America/Araguaina": "America/Araguaina",
                            "Asia/Ujung_Pandang": "Asia/Ujung_Pandang",
                            "Cuba": "Cuba",
                            "America/St_Lucia": "America/St_Lucia",
                            "Pacific/Kiritimati": "Pacific/Kiritimati",
                            "Asia/Yakutsk": "Asia/Yakutsk",
                            "Indian/Mahe": "Indian/Mahe",
                            "America/Panama": "America/Panama",
                            "Asia/Hong_Kong": "Asia/Hong_Kong",
                            "Europe/Gibraltar": "Europe/Gibraltar",
                            "America/Scoresbysund": "America/Scoresbysund",
                            "SystemV/YST9YDT": "SystemV/YST9YDT",
                            "America/Aruba": "America/Aruba",
                            "Asia/Muscat": "Asia/Muscat",
                            "EAT": "EAT",
                            "Africa/Freetown": "Africa/Freetown",
                            "America/Argentina/San_Luis": "America/Argentina/San_Luis",
                            "America/Paramaribo": "America/Paramaribo",
                            "Australia/Lindeman": "Australia/Lindeman",
                            "Asia/Hovd": "Asia/Hovd",
                            "America/Bahia": "America/Bahia",
                            "CAT": "CAT",
                            "Pacific/Pohnpei": "Pacific/Pohnpei",
                            "Pacific/Guadalcanal": "Pacific/Guadalcanal",
                            "Australia/Perth": "Australia/Perth",
                            "Pacific/Pago_Pago": "Pacific/Pago_Pago",
                            "Libya": "Libya",
                            "America/Edmonton": "America/Edmonton",
                            "Antarctica/Syowa": "Antarctica/Syowa",
                            "America/Los_Angeles": "America/Los_Angeles",
                            "America/Knox_IN": "America/Knox_IN",
                            "Asia/Chungking": "Asia/Chungking",
                            "America/Creston": "America/Creston",
                            "Australia/Canberra": "Australia/Canberra",
                            "Africa/Nouakchott": "Africa/Nouakchott",
                            "America/Noronha": "America/Noronha",
                            "Asia/Riyadh89": "Asia/Riyadh89",
                            "America/La_Paz": "America/La_Paz",
                            "Asia/Riyadh88": "Asia/Riyadh88",
                            "ECT": "ECT",
                            "Mexico/General": "Mexico/General",
                            "America/Dominica": "America/Dominica",
                            "Asia/Riyadh87": "Asia/Riyadh87",
                            "Asia/Saigon": "Asia/Saigon",
                            "Antarctica/Macquarie": "Antarctica/Macquarie",
                            "MST7MDT": "MST7MDT",
                            "Africa/El_Aaiun": "Africa/El_Aaiun",
                            "Africa/Ceuta": "Africa/Ceuta",
                            "Europe/Andorra": "Europe/Andorra",
                            "Africa/Luanda": "Africa/Luanda",
                            "Africa/Addis_Ababa": "Africa/Addis_Ababa",
                            "America/Atikokan": "America/Atikokan",
                            "America/St_Barthelemy": "America/St_Barthelemy",
                            "America/Argentina/Salta": "America/Argentina/Salta",
                            "America/Kralendijk": "America/Kralendijk",
                            "Asia/Beirut": "Asia/Beirut",
                            "NET": "NET",
                            "Pacific/Nauru": "Pacific/Nauru",
                            "Africa/Brazzaville": "Africa/Brazzaville",
                            "Jamaica": "Jamaica",
                            "Etc/Zulu": "Etc/Zulu",
                            "America/Guadeloupe": "America/Guadeloupe",
                            "Africa/Bangui": "Africa/Bangui",
                            "Asia/Kamchatka": "Asia/Kamchatka",
                            "Asia/Ulan_Bator": "Asia/Ulan_Bator",
                            "Asia/Aqtau": "Asia/Aqtau",
                            "America/Eirunepe": "America/Eirunepe",
                            "Africa/Lubumbashi": "Africa/Lubumbashi",
                            "Antarctica/Palmer": "Antarctica/Palmer",
                            "Asia/Kolkata": "Asia/Kolkata",
                            "Pacific/Galapagos": "Pacific/Galapagos",
                            "America/Monterrey": "America/Monterrey",
                            "Europe/London": "Europe/London",
                            "SystemV/EST5EDT": "SystemV/EST5EDT",
                            "Europe/Samara": "Europe/Samara",
                            "Europe/Monaco": "Europe/Monaco",
                            "America/Indiana/Indianapolis": "America/Indiana/Indianapolis",
                            "Atlantic/Bermuda": "Atlantic/Bermuda",
                            "Indian/Christmas": "Indian/Christmas",
                            "Pacific/Tarawa": "Pacific/Tarawa",
                            "America/Yakutat": "America/Yakutat",
                            "Europe/Vienna": "Europe/Vienna",
                            "America/St_Vincent": "America/St_Vincent",
                            "GMT0": "GMT0",
                            "America/Port-au-Prince": "America/Port-au-Prince",
                            "America/New_York": "America/New_York",
                            "America/Ensenada": "America/Ensenada",
                            "Africa/Mogadishu": "Africa/Mogadishu",
                            "Pacific/Niue": "Pacific/Niue",
                            "Asia/Qatar": "Asia/Qatar",
                            "Africa/Gaborone": "Africa/Gaborone",
                            "America/Antigua": "America/Antigua",
                            "Asia/Thimbu": "Asia/Thimbu",
                            "SystemV/CST6CDT": "SystemV/CST6CDT",
                            "Australia/Lord_Howe": "Australia/Lord_Howe",
                            "Europe/Lisbon": "Europe/Lisbon",
                            "Europe/Zurich": "Europe/Zurich",
                            "America/Montevideo": "America/Montevideo",
                            "Asia/Macao": "Asia/Macao",
                            "America/Winnipeg": "America/Winnipeg",
                            "America/Guyana": "America/Guyana",
                            "Asia/Tel_Aviv": "Asia/Tel_Aviv",
                            "America/Santarem": "America/Santarem",
                            "Asia/Macau": "Asia/Macau",
                            "Europe/Dublin": "Europe/Dublin",
                            "Europe/Belfast": "Europe/Belfast",
                            "Asia/Vladivostok": "Asia/Vladivostok",
                            "Europe/Zaporozhye": "Europe/Zaporozhye",
                            "Canada/Saskatchewan": "Canada/Saskatchewan",
                            "Australia/NSW": "Australia/NSW",
                            "Iceland": "Iceland",
                            "Indian/Mayotte": "Indian/Mayotte",
                            "Canada/Mountain": "Canada/Mountain",
                            "Africa/Ndjamena": "Africa/Ndjamena",
                            "America/Tijuana": "America/Tijuana",
                            "Pacific/Tahiti": "Pacific/Tahiti",
                            "Africa/Monrovia": "Africa/Monrovia",
                            "ACT": "ACT",
                            "Asia/Qyzylorda": "Asia/Qyzylorda",
                            "Europe/Copenhagen": "Europe/Copenhagen",
                            "America/Thule": "America/Thule",
                            "Europe/Amsterdam": "Europe/Amsterdam",
                            "Asia/Thimphu": "Asia/Thimphu",
                            "America/Chihuahua": "America/Chihuahua",
                            "America/Yellowknife": "America/Yellowknife",
                            "Africa/Windhoek": "Africa/Windhoek",
                            "America/Cayman": "America/Cayman",
                            "Antarctica/Davis": "Antarctica/Davis",
                            "Europe/Berlin": "Europe/Berlin",
                            "Africa/Kinshasa": "Africa/Kinshasa",
                            "Asia/Omsk": "Asia/Omsk",
                            "Asia/Kathmandu": "Asia/Kathmandu",
                            "Europe/Chisinau": "Europe/Chisinau",
                            "Asia/Choibalsan": "Asia/Choibalsan",
                            "Etc/UCT": "Etc/UCT",
                            "BET": "BET",
                            "Europe/Jersey": "Europe/Jersey",
                            "CET": "CET",
                            "Etc/Universal": "Etc/Universal",
                            "Europe/Prague": "Europe/Prague",
                            "Africa/Harare": "Africa/Harare",
                            "America/Toronto": "America/Toronto",
                            "Pacific/Samoa": "Pacific/Samoa",
                            "Egypt": "Egypt",
                            "America/Montserrat": "America/Montserrat",
                            "Pacific/Honolulu": "Pacific/Honolulu",
                            "America/Miquelon": "America/Miquelon",
                            "Africa/Sao_Tome": "Africa/Sao_Tome",
                            "America/Kentucky/Louisville": "America/Kentucky/Louisville",
                            "Asia/Pyongyang": "Asia/Pyongyang",
                            "Europe/Tiraspol": "Europe/Tiraspol",
                            "America/Porto_Velho": "America/Porto_Velho",
                            "Pacific/Truk": "Pacific/Truk",
                            "America/Costa_Rica": "America/Costa_Rica",
                            "Iran": "Iran",
                            "America/Indianapolis": "America/Indianapolis",
                            "America/Fortaleza": "America/Fortaleza",
                            "America/Mexico_City": "America/Mexico_City",
                            "America/El_Salvador": "America/El_Salvador",
                            "AET": "AET",
                            "Europe/Kaliningrad": "Europe/Kaliningrad",
                            "Asia/Kashgar": "Asia/Kashgar",
                            "Asia/Damascus": "Asia/Damascus",
                            "SystemV/PST8": "SystemV/PST8",
                            "America/Port_of_Spain": "America/Port_of_Spain",
                            "America/Kentucky/Monticello": "America/Kentucky/Monticello",
                            "CST6CDT": "CST6CDT",
                            "America/Halifax": "America/Halifax",
                            "Asia/Karachi": "Asia/Karachi",
                            "EST5EDT": "EST5EDT",
                            "America/North_Dakota/Beulah": "America/North_Dakota/Beulah",
                            "America/Managua": "America/Managua",
                            "Pacific/Wallis": "Pacific/Wallis",
                            "America/Nome": "America/Nome",
                            "Africa/Bujumbura": "Africa/Bujumbura",
                            "Atlantic/Faeroe": "Atlantic/Faeroe",
                            "America/Rio_Branco": "America/Rio_Branco",
                            "Asia/Khandyga": "Asia/Khandyga",
                            "Europe/Podgorica": "Europe/Podgorica",
                            "America/Santiago": "America/Santiago",
                            "Mexico/BajaSur": "Mexico/BajaSur",
                            "America/Vancouver": "America/Vancouver",
                            "Asia/Bahrain": "Asia/Bahrain",
                            "W-SU": "W-SU",
                            "America/Indiana/Vincennes": "America/Indiana/Vincennes",
                            "Pacific/Wake": "Pacific/Wake",
                            "Pacific/Enderbury": "Pacific/Enderbury",
                            "Etc/Greenwich": "Etc/Greenwich",
                            "Europe/Oslo": "Europe/Oslo",
                            "America/Guatemala": "America/Guatemala",
                            "Europe/Vatican": "Europe/Vatican",
                            "America/Montreal": "America/Montreal",
                            "Asia/Dubai": "Asia/Dubai",
                            "Asia/Harbin": "Asia/Harbin",
                            "US/Pacific-New": "US/Pacific-New",
                            "Australia/South": "Australia/South",
                            "US/Eastern": "US/Eastern",
                            "Africa/Johannesburg": "Africa/Johannesburg",
                            "Europe/Tallinn": "Europe/Tallinn",
                            "America/Ojinaga": "America/Ojinaga",
                            "Europe/Uzhgorod": "Europe/Uzhgorod",
                            "America/Barbados": "America/Barbados",
                            "Asia/Ust-Nera": "Asia/Ust-Nera",
                            "Asia/Urumqi": "Asia/Urumqi",
                            "AGT": "AGT",
                            "MIT": "MIT",
                            "US/Central": "US/Central",
                            "America/Louisville": "America/Louisville",
                            "Asia/Gaza": "Asia/Gaza",
                            "Atlantic/Azores": "Atlantic/Azores",
                            "Chile/Continental": "Chile/Continental",
                            "America/Lower_Princes": "America/Lower_Princes",
                            "Asia/Kuwait": "Asia/Kuwait",
                            "Africa/Lagos": "Africa/Lagos",
                            "Africa/Porto-Novo": "Africa/Porto-Novo",
                            "US/Hawaii": "US/Hawaii",
                            "Africa/Accra": "Africa/Accra",
                            "Pacific/Port_Moresby": "Pacific/Port_Moresby",
                            "America/Blanc-Sablon": "America/Blanc-Sablon",
                            "Africa/Juba": "Africa/Juba",
                            "US/Arizona": "US/Arizona",
                            "America/Marigot": "America/Marigot",
                            "Mideast/Riyadh87": "Mideast/Riyadh87",
                            "Mideast/Riyadh88": "Mideast/Riyadh88",
                            "Mideast/Riyadh89": "Mideast/Riyadh89",
                            "America/Indiana/Knox": "America/Indiana/Knox",
                            "Pacific/Noumea": "Pacific/Noumea",
                            "Europe/Kiev": "Europe/Kiev",
                            "Asia/Dushanbe": "Asia/Dushanbe",
                            "Europe/Isle_of_Man": "Europe/Isle_of_Man",
                            "HST": "HST",
                            "Australia/Tasmania": "Australia/Tasmania",
                            "America/Jamaica": "America/Jamaica",
                            "CNT": "CNT",
                            "Asia/Tokyo": "Asia/Tokyo",
                            "PNT": "PNT",
                            "Indian/Maldives": "Indian/Maldives",
                            "Africa/Abidjan": "Africa/Abidjan",
                            "Pacific/Pitcairn": "Pacific/Pitcairn",
                            "Europe/Malta": "Europe/Malta",
                            "Europe/Madrid": "Europe/Madrid",
                            "Atlantic/Reykjavik": "Atlantic/Reykjavik",
                            "Asia/Kabul": "Asia/Kabul",
                            "Asia/Magadan": "Asia/Magadan",
                            "Zulu": "Zulu",
                            "America/Argentina/Rio_Gallegos": "America/Argentina/Rio_Gallegos",
                            "Australia/Melbourne": "Australia/Melbourne",
                            "Indian/Antananarivo": "Indian/Antananarivo",
                            "Asia/Pontianak": "Asia/Pontianak",
                            "Africa/Mbabane": "Africa/Mbabane",
                            "Pacific/Kwajalein": "Pacific/Kwajalein",
                            "Africa/Banjul": "Africa/Banjul",
                            "America/Argentina/Jujuy": "America/Argentina/Jujuy",
                            "America/Anchorage": "America/Anchorage",
                            "America/Argentina/La_Rioja": "America/Argentina/La_Rioja",
                            "Africa/Khartoum": "Africa/Khartoum",
                            "Africa/Tripoli": "Africa/Tripoli",
                            "Pacific/Marquesas": "Pacific/Marquesas",
                            "Asia/Rangoon": "Asia/Rangoon",
                            "Canada/Atlantic": "Canada/Atlantic",
                            "America/Jujuy": "America/Jujuy",
                            "America/Buenos_Aires": "America/Buenos_Aires",
                            "Asia/Calcutta": "Asia/Calcutta",
                            "Europe/Bucharest": "Europe/Bucharest",
                            "America/Atka": "America/Atka",
                            "Europe/Athens": "Europe/Athens",
                            "America/Puerto_Rico": "America/Puerto_Rico",
                            "US/Mountain": "US/Mountain",
                            "Chile/EasterIsland": "Chile/EasterIsland",
                            "GMT": "GMT",
                            "Kwajalein": "Kwajalein",
                            "Canada/Yukon": "Canada/Yukon",
                            "America/Nassau": "America/Nassau",
                            "America/Swift_Current": "America/Swift_Current",
                            "America/Havana": "America/Havana",
                            "Asia/Jayapura": "Asia/Jayapura",
                            "Europe/San_Marino": "Europe/San_Marino",
                            "Pacific/Gambier": "Pacific/Gambier",
                            "America/Argentina/Mendoza": "America/Argentina/Mendoza",
                            "VST": "VST",
                            "Europe/Ljubljana": "Europe/Ljubljana",
                            "Australia/LHI": "Australia/LHI",
                            "America/Rainy_River": "America/Rainy_River",
                            "America/Belem": "America/Belem",
                            "America/Sao_Paulo": "America/Sao_Paulo",
                            "Pacific/Easter": "Pacific/Easter",
                            "America/Menominee": "America/Menominee",
                            "Brazil/DeNoronha": "Brazil/DeNoronha",
                            "America/Juneau": "America/Juneau",
                            "Pacific/Fakaofo": "Pacific/Fakaofo",
                            "SST": "SST",
                            "Japan": "Japan",
                            "America/Mendoza": "America/Mendoza",
                            "America/Martinique": "America/Martinique",
                            "Africa/Conakry": "Africa/Conakry",
                            "PRT": "PRT",
                            "IST": "IST",
                            "Australia/ACT": "Australia/ACT",
                            "Africa/Timbuktu": "Africa/Timbuktu",
                            "America/North_Dakota/New_Salem": "America/North_Dakota/New_Salem",
                            "America/Adak": "America/Adak",
                            "US/Alaska": "US/Alaska",
                            "NST": "NST",
                            "America/Godthab": "America/Godthab",
                            "Africa/Libreville": "Africa/Libreville",
                            "Pacific/Kosrae": "Pacific/Kosrae",
                            "America/St_Thomas": "America/St_Thomas",
                            "Asia/Ashkhabad": "Asia/Ashkhabad",
                            "PRC": "PRC",
                            "Etc/GMT+7": "Etc/GMT+7",
                            "Etc/GMT+6": "Etc/GMT+6",
                            "UTC": "UTC",
                            "Europe/Minsk": "Europe/Minsk",
                            "Etc/GMT+5": "Etc/GMT+5",
                            "Etc/GMT+4": "Etc/GMT+4",
                            "Pacific/Efate": "Pacific/Efate",
                            "Etc/GMT+3": "Etc/GMT+3",
                            "MST": "MST",
                            "Etc/GMT+2": "Etc/GMT+2",
                            "America/Shiprock": "America/Shiprock",
                            "Etc/GMT+1": "Etc/GMT+1",
                            "Etc/GMT+0": "Etc/GMT+0",
                            "CST": "CST",
                            "Asia/Yekaterinburg": "Asia/Yekaterinburg",
                            "Pacific/Tongatapu": "Pacific/Tongatapu",
                            "PST": "PST",
                            "Europe/Riga": "Europe/Riga",
                            "America/Guayaquil": "America/Guayaquil",
                            "Canada/Newfoundland": "Canada/Newfoundland",
                            "Pacific/Yap": "Pacific/Yap",
                            "America/Grand_Turk": "America/Grand_Turk",
                            "Asia/Manila": "Asia/Manila",
                            "Asia/Jakarta": "Asia/Jakarta",
                            "Asia/Ashgabat": "Asia/Ashgabat",
                            "Africa/Kigali": "Africa/Kigali",
                            "America/Santo_Domingo": "America/Santo_Domingo",
                            "America/Argentina/Buenos_Aires": "America/Argentina/Buenos_Aires",
                            "Antarctica/Mawson": "Antarctica/Mawson",
                            "Hongkong": "Hongkong",
                            "EST": "EST",
                            "America/Goose_Bay": "America/Goose_Bay",
                            "Europe/Tirane": "Europe/Tirane",
                            "America/Nipigon": "America/Nipigon",
                            "Asia/Chongqing": "Asia/Chongqing",
                            "America/Cayenne": "America/Cayenne",
                            "Asia/Samarkand": "Asia/Samarkand",
                            "Israel": "Israel",
                            "US/Indiana-Starke": "US/Indiana-Starke",
                            "Pacific/Fiji": "Pacific/Fiji",
                            "Europe/Nicosia": "Europe/Nicosia",
                            "Brazil/West": "Brazil/West",
                            "Australia/Darwin": "Australia/Darwin",
                            "Etc/GMT-1": "Etc/GMT-1",
                            "Europe/Skopje": "Europe/Skopje",
                            "Etc/GMT-0": "Etc/GMT-0",
                            "Australia/Adelaide": "Australia/Adelaide",
                            "Etc/GMT-5": "Etc/GMT-5",
                            "Etc/GMT-4": "Etc/GMT-4",
                            "Etc/GMT-3": "Etc/GMT-3",
                            "Asia/Riyadh": "Asia/Riyadh",
                            "Etc/GMT-2": "Etc/GMT-2",
                            "Etc/GMT-9": "Etc/GMT-9",
                            "Asia/Aden": "Asia/Aden",
                            "Etc/GMT-8": "Etc/GMT-8",
                            "Africa/Casablanca": "Africa/Casablanca",
                            "Asia/Krasnoyarsk": "Asia/Krasnoyarsk",
                            "Canada/Eastern": "Canada/Eastern",
                            "Pacific/Johnston": "Pacific/Johnston",
                            "Etc/GMT-7": "Etc/GMT-7",
                            "Pacific/Midway": "Pacific/Midway",
                            "Etc/GMT-6": "Etc/GMT-6",
                            "Etc/GMT+8": "Etc/GMT+8",
                            "Etc/GMT+9": "Etc/GMT+9",
                            "Pacific/Palau": "Pacific/Palau",
                            "SystemV/CST6": "SystemV/CST6",
                            "Asia/Kuala_Lumpur": "Asia/Kuala_Lumpur",
                            "Europe/Bratislava": "Europe/Bratislava",
                            "Europe/Zagreb": "Europe/Zagreb",
                            "Canada/Central": "Canada/Central",
                            "Australia/North": "Australia/North",
                            "Singapore": "Singapore",
                            "Europe/Warsaw": "Europe/Warsaw",
                            "Etc/GMT0": "Etc/GMT0",
                            "Africa/Lome": "Africa/Lome",
                            "America/Sitka": "America/Sitka",
                            "Atlantic/Madeira": "Atlantic/Madeira"
                        }
                    },
                    {
                        "id": "on",
                        "title": "Select the weekday for your email delivery.",
                        "fieldType": "select",
                        "name": "on",
                        "ismultiple": "true",
                        "label": "On",
                        "type": "select",
                        "required": "required",
                        "multiple": "multiple",
                        "options": {
                            "Thu": "Thu",
                            "Sun": "Sun",
                            "Wed": "Wed",
                            "Sat-Sun": "Sat-Sun",
                            "Mon-Fri": "Mon-Fri",
                            "Any Day": "any_day",
                            "Sat": "Sat",
                            "Mon-Sat": "Mon-Sat",
                            "Fri": "Fri",
                            "Tue": "Tue",
                            "Mon": "Mon"
                        }
                    },
                    {
                        "id": "at",
                        "title": "Select the time for your email delivery.",
                        "fieldType": "select",
                        "name": "at",
                        "ismultiple": "true",
                        "label": "At",
                        "type": "select",
                        "required": "required",
                        "multiple": "multiple",
                        "options": {
                            "10:00 PM": "22:00",
                            "11:00 PM": "23:00",
                            "6:00 PM": "18:00",
                            "4:00 PM": "16:00",
                            "10:00 AM": "10:00",
                            "11:00 AM": "11:00",
                            "2:00 AM": "02:00",
                            "5:30 AM": "05:30",
                            "5:00 AM": "05:00",
                            "11:30 AM": "11:30",
                            "6:30 PM": "18:30",
                            "4:30 AM": "04:30",
                            "9:00 AM": "09:00",
                            "5:00 PM": "17:00",
                            "10:30 AM": "10:30",
                            "1:00 AM": "01:00",
                            "4:00 AM": "04:00",
                            "7:00 PM": "19:00",
                            "7:30 AM": "07:30",
                            "8:00 AM": "08:00",
                            "1:30 AM": "01:30",
                            "7:30 PM": "19:30",
                            "3:00 PM": "15:00",
                            "12:00 PM": "12:00",
                            "12:30 PM": "12:30",
                            "7:00 AM": "07:00",
                            "8:30 AM": "08:30",
                            "1:00 PM": "13:00",
                            "1:30 PM": "13:30",
                            "6:00 AM": "06:00",
                            "3:00 AM": "03:00",
                            "8:00 PM": "20:00",
                            "2:30 PM": "14:30",
                            "9:30 AM": "09:30",
                            "6:30 AM": "06:30",
                            "3:30 AM": "03:30",
                            "Any Time": "any_time",
                            "8:30 PM": "20:30",
                            "3:30 PM": "15:30",
                            "10:30 PM": "22:30",
                            "4:30 PM": "16:30",
                            "9:30 PM": "21:30",
                            "2:30 AM": "02:30",
                            "12:30 AM": "00:30",
                            "5:30 PM": "17:30",
                            "2:00 PM": "14:00",
                            "12:00 AM": "00:01",
                            "9:00 PM": "21:00",
                            "11:30 PM": "23:30"
                        }
                    },
                    {
                        "category": "Help",
                        "fieldType": "label",
                        "label": "Send email in TEXT or HTML format. You can choose from email-id and name, and optionally specify a different email-id the replies should go to.<br/><br/>You can track if the links in your email are clicked by the recepient. You can set a time when the email should be delivered to the recepient.",
                        "type": "label"
                    }
                ],
                "icon": "json/nodes/icons/email/sendemail.png",
                "workflow_tasklet_class_name": "com.campaignio.tasklets.agile.SendEmail",
                "url": "json/nodes/email/send_email.jsp",
                "info": "Send email in text or HTML format. You can choose your delivery day and time.",
                "author": "John",
                "help": "Send email in text or HTML format. You can choose your delivery day and time.",
                "category": "Email",
                "thumbnail": "json/nodes/images/email/sendemail.png",
                "name": "Send Email",
                "company": "mantra",
                "language": "en",
                "branches": "yes"
            },
            "id": "PBXHWo1PHDnoJ",
            "xPosition": 460,
            "yPosition": 144,
            "displayname": "Send Newsletter ",
            "JsonValues": [
                {
                    "name": "nodename",
                    "value": "Send Newsletter "
                },
                {
                    "name": "from_name",
                    "value": "Updates"
                },
                {
                    "name": "from_email",
                    "value": "updates@mycompany.com"
                },
                {
                    "name": "to_email",
                    "value": "{{email}}"
                },
                {
                    "name": "cc_email",
                    "value": ""
                },
                {
                    "name": "subject",
                    "value": "Here what's happening from our end"
                },
                {
                    "name": "replyto_email",
                    "value": ""
                },
                {
                    "name": "merge_fields",
                    "value": ""
                },
                {
                    "name": "text_email",
                    "value": "\r\nText version of newsletter here."
                },
                {
                    "name": "merge_fields",
                    "value": ""
                },
                {
                    "name": "html_email",
                    "value": "<div style=\"background-color: #f2f2f2; margin: 0; padding: 0; min-height: 100%!important; width: 100%!important;\"><center>\r\n<table style=\"background-color: #f2f2f2; margin: 0px; padding: 0px; border-collapse: collapse !important; min-height: 100% !important; width: 100% !important;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 40px 20px; margin: 0; min-height: 100%!important; width: 100%!important;\" align=\"center\" valign=\"top\">\r\n<table style=\"width: 600px; border-collapse: collapse!important;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"center\" valign=\"top\"><a style=\"text-decoration: none;\" title=\"Your Logo here\" href=\"https://www.yoursite.com\" target=\"_blank\"> <img style=\"border: 0; color: #6dc6dd!important; font-family: Helvetica,Arial,sans-serif; font-size: 60px; font-weight: bold; min-height: auto!important; letter-spacing: -4px; line-height: 100%; outline: none; text-align: center; text-decoration: none;\" src=\"https://www.MYSITE.com/img/logo.png\" alt=\"Your Logo here\" /> </a></td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding-top: 30px; padding-bottom: 30px;\" align=\"center\" valign=\"top\">\r\n<table style=\"background-color: #ffffff; border-collapse: separate !important; border-top-left-radius: 4px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding-right: 40px; padding-left: 40px;\" align=\"center\" valign=\"top\">\r\n<table style=\"border-collapse: collapse !important; width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"center\" valign=\"top\" width=\"\">\r\n<table style=\"border-collapse: collapse !important; width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" valign=\"top\" width=\"75px\">\r\n<table style=\"border-collapse: collapse !important; background-color: #6dc6dd; width: 75px;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 40px 15px 5px; text-align: center; color: #ffffff; line-height: 100%; font-family: Helvetica,Arial,sans-serif; font-size: 14px; font-weight: bold;\" align=\"center\" valign=\"bottom\">Digest</td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding: 5px 15px 20px; text-align: center; color: #ffffff; line-height: 100%; font-family: Helvetica,Arial,sans-serif; font-size: 40px; font-weight: bold;\" align=\"center\" valign=\"top\">1</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td style=\"padding-top: 40px; padding-left: 40px; color: #606060; font-family: Helvetica,Arial,sans-serif; font-size: 15px; line-height: 150%; text-align: left;\" align=\"left\" valign=\"top\">\r\n<h1 style=\"font-family: Helvetica,Arial,sans-serif; font-size: 40px; font-weight: bold; letter-spacing: -1px; line-height: 115%; margin: 0; padding: 0; text-align: left; color: #606060!important; text-decoration: none!important;\">Title</h1>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"color: #606060; font-family: Helvetica,Arial,sans-serif; font-size: 15px; line-height: 150%; text-align: left; padding: 40px;\" align=\"center\" valign=\"top\">\r\n<p>Hello&nbsp;{{first_name}},</p>\r\n<p>Some introductory text</p>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding-bottom: 30px;\" align=\"center\" valign=\"top\">\r\n<table style=\"border-collapse: collapse !important; width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"border-top: 2px solid #f2f2f2; padding-top: 40px; padding-right: 40px; padding-bottom: 30px; padding-left: 40px; color: #606060; font-family: Helvetica,Arial,sans-serif; font-size: 15px; line-height: 150%; text-align: left;\" align=\"center\" valign=\"top\">\r\n<h3 style=\"font-family: Helvetica,Arial,sans-serif; font-size: 18px; font-weight: bold; letter-spacing: -.5px; line-height: 115%; margin: 0; padding: 0; text-align: center; color: #606060!important; text-decoration: none!important;\">News Item 1</h3>\r\n<p>Text here.</p>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding-right: 40px; padding-left: 40px;\" align=\"center\" valign=\"top\"><img style=\"border: 1px solid #c8c8c8; border-radius: 5px;\" src=\"https://www.yoursite.com/image1.png\" alt=\"insert image 1\" /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding-bottom: 30px;\" align=\"center\" valign=\"top\">\r\n<table style=\"border-collapse: collapse !important; width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"border-top: 2px solid #f2f2f2; padding-top: 40px; padding-right: 40px; padding-bottom: 30px; padding-left: 40px; color: #606060; font-family: Helvetica,Arial,sans-serif; font-size: 15px; line-height: 150%; text-align: left;\" align=\"center\" valign=\"top\">\r\n<h3 style=\"font-family: Helvetica,Arial,sans-serif; font-size: 18px; font-weight: bold; letter-spacing: -.5px; line-height: 115%; margin: 0; padding: 0; text-align: center; color: #606060!important; text-decoration: none!important;\">News Item 2</h3>\r\n<p>Text here.</p>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding-right: 40px; padding-left: 40px;\" align=\"center\" valign=\"top\"><img style=\"border: 1px solid #c8c8c8; border-radius: 5px;\" src=\"https://www.agilecrm.com/img/email-images/ScreenShot2013-09-02at20334PM.png\" alt=\"Triggers\" /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding-bottom: 30px;\" align=\"center\" valign=\"top\">\r\n<table style=\"border-collapse: collapse !important; width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"border-top: 2px solid #f2f2f2; padding-top: 40px; padding-right: 40px; padding-bottom: 30px; padding-left: 40px; color: #606060; font-family: Helvetica,Arial,sans-serif; font-size: 15px; line-height: 150%; text-align: left;\" align=\"center\" valign=\"top\">\r\n<h3 style=\"font-family: Helvetica,Arial,sans-serif; font-size: 18px; font-weight: bold; letter-spacing: -.5px; line-height: 115%; margin: 0; padding: 0; text-align: center; color: #606060!important; text-decoration: none!important;\">News Item 3</h3>\r\n<p>Text here.</p>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding-right: 40px; padding-left: 40px;\" align=\"center\" valign=\"top\"><img style=\"border: 1px solid #c8c8c8; border-radius: 5px;\" src=\"https://www.agilecrm.com/img/email-images/users.png\" alt=\"Campaign Authentication\" /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"padding-right: 40px; padding-bottom: 40px; padding-left: 40px;\" align=\"center\" valign=\"middle\">\r\n<table style=\"background-color: #6dc6dd; border-collapse: separate!important; border-radius: 3px;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"color: #ffffff; font-family: Helvetica,Arial,sans-serif; font-size: 15px; font-weight: bold; line-height: 100%; padding-top: 18px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px;\" align=\"center\" valign=\"middle\"><a style=\"color: #ffffff; text-decoration: none;\" href=\"https://www.MYSITE.com/newsletter\" target=\"_blank\">C</a>all To Action</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align=\"center\" valign=\"top\">\r\n<table style=\"border-collapse: collapse !important; width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"color: #606060; font-family: Helvetica,Arial,sans-serif; font-size: 13px; line-height: 125%;\" align=\"center\" valign=\"top\">\r\n<p style=\"margin: -5px;\"><img style=\"vertical-align: middle;\" src=\"https://www.MYSITE.com/logo.png\" alt=\"\" /> Your Caption</p>\r\n<p style=\"margin: 10px;\"><a style=\"padding: 6px; color: black; border: none;\" href=\"https://twitter.com/agile_crm\" target=\"_blank\"><img style=\"border: none;\" src=\"https://www.agilecrm.com/img/twitter-icon.png\" alt=\"twitter\" /></a> <a style=\"padding: 6px; border: none;\" href=\"https://www.facebook.com/CRM.Agile\" target=\"_blank\"><img style=\"border: none;\" src=\"https://www.agilecrm.com/img/facebook-icon.png\" alt=\"fb\" /></a> <a style=\"padding: 6px; border: none;\" href=\"https://plus.google.com/109484059291748745615/posts\" target=\"_blank\"><img style=\"border: none;\" src=\"https://www.agilecrm.com/img/googleplus-icon.png\" alt=\"gplus\" /></a></p>\r\n<p><a href=\"https://www.agilecrm.com\" target=\"_blank\">www.mysite.com</a></p>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align=\"center\" valign=\"top\">&nbsp;</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</center></div>"
                },
                {
                    "name": "track_clicks",
                    "value": "yes"
                },
                {
                    "name": "purl_keyword",
                    "value": ""
                },
                {
                    "name": "time_zone",
                    "value": "ACT"
                },
                {
                    "name": "on",
                    "value": "any_day"
                },
                {
                    "name": "at",
                    "value": "any_time"
                }
            ],
            "States": [
                {
                    "yes": "hangup"
                }
            ]
        }
    ]
}