cd C:\Users\invox-4\projects-github\agile-java-server\war
type tpl\*.html > C:\Users\invox-4\projects-github\agile-java-server\war\tpl.js
type tpl\settings\*.html > C:\Users\invox-4\projects-github\agile-java-server\war\settings.js
type tpl\continue\*.html > C:\Users\invox-4\projects-github\agile-java-server\war\continue.js
type tpl\admin-settings\*.html > C:\Users\invox-4\projects-github\agile-java-server\war\admin-settings.js
cd C:\Users\invox-4\projects-github\agile-java-server\util

